name: Feature request triage bot

on: [workflow_dispatch]

jobs:
  feature_triage:
    if: github.repository == 'SampleWorkflow/feature-handling-demo'
    runs-on: ubuntu-latest
    steps:
      - uses: mgechev/dev-infra/github-actions/feature-request@4f335a4c1f01f20bf905acee2d68c7248f50f2a0
        with:
          token: ${{ secrets.FEATURE_REQUEST_BOT_TOKEN }}
          repository: 'feature-handling-demo'
          minimum-unique-comment-authors-for-consideration: 10
          minimum-votes-for-consideration: 1
          feature-request-label: 'feature'
          in-backlog-label: 'in-backlog'
          requires-votes-label: 'votes-required'
          under-consideration-label: 'under-consideration'
          insufficient-votes-label: 'insufficient-votes'
          close-when-no-sufficient-votes: false
          old-issue-warn-days-duration: 0.03
          warn-days-duration: 0.03
          close-after-warn-days-duration: 0.05
